name: Composer (php-actions)
uses: php-actions/composer@v6
with:
  php_version: 8.0

on:
  push:
    branches: ['dev']
    path:
      - .github/**
      - src/**
      - composer.lock
      - composer.json
  pull_request:
    branches: ['dev']
    path:
      - .github/**
      - src/**
      - composer.lock
      - composer.json

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php

    - name: Install dependencies
      run: composer install --no-progress -o -a

    - name: Run Psalm
      run: composer run-script psalm

    - name: Run PHPLint
      run: composer run-script phplint
