name: CI

on:
  push:
    branches: ['dev']
    path:
      - .github/**
      - src/**
      - composer.lock
      - composer.json
  pull_request:
    branches: ['dev']
    path:
      - .github/**
      - src/**
      - composer.lock
      - composer.json

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
        
    - name: Validate composer.json and composer.lock
      uses: php-actions/composer@v6
      with:
        - php_version: 8.0
        - command: validate
        - args: --strict

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        - php_version: 8.0
        - command: install
        - args: -o -a
        - progress: no

    - name: Run Psalm
      uses: php-actions/composer@v6
      with:
        - php_version: 8.0
        - command: run-script
        - args: psalm

    - name: Run PHPLint
      uses: php-actions/composer@v6
      with:
        - php_version: 8.0
        - command: run-script
        - args: phplint
